apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-controller-full-access
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: harness-gitops
roleRef:
  kind: ClusterRole
  name: argocd-controller-full-access
  apiGroup: rbac.authorization.k8s.io

